# Generated by Django 6.0.4 on 2026-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Stopped', 'Stopped'), ('Maintenance', 'Maintenance')], default='Running', max_length=20)),
                ('production_rate', models.IntegerField(help_text='Items produced per hour')),
                ('working_hours', models.IntegerField()),
            ],
        ),
    ]
