# Generated by Django 6.0.4 on 2026-06-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_health',
            field=models.FloatField(default=100.0, help_text='Machine health score from 0 to 100'),
        ),
        migrations.AddField(
            model_name='machine',
            name='target_production',
            field=models.IntegerField(default=0, help_text='Target number of items to be produced'),
        ),
        migrations.AddField(
            model_name='machine',
            name='temperature',
            field=models.FloatField(default=0.0, help_text='Current machine temperature in °C'),
        ),
    ]
