"""
Django settings for digital_twin_API project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
========================================
  settings.py — Django Project Settings
  Digital Twin Factory API
========================================

  This file configures the entire Django project:
  - Security keys and debug mode
  - Installed apps (Django, DRF, Swagger, Factory)
  - Database (SQLite)
  - REST Framework renderers
  - Static files and internationalization
"""

from pathlib import Path

# --------------------------------------------------
# Base Directory
# Root of the project (two levels up from this file)
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------
# Security Settings
# --------------------------------------------------

# Secret key used for cryptographic signing (keep private in production)
SECRET_KEY = 'django-insecure-a_2jc5$9%zu(5@k0t)qn7_7u_$3)n()ql(=apcu!yeo@dx!o8y'

# Enable debug mode for development (set False in production)
DEBUG = False

# Hosts allowed to connect to this Django server
ALLOWED_HOSTS = ['*']

# --------------------------------------------------
# Installed Applications
# Django loads these apps on startup
# --------------------------------------------------
INSTALLED_APPS = [

    # --- Default Django Apps ---
    'django.contrib.admin',        # Admin panel
    'django.contrib.auth',         # User authentication
    'django.contrib.contenttypes', # Content type framework
    'django.contrib.sessions',     # Session management
    'django.contrib.messages',     # Flash messages
    'django.contrib.staticfiles',  # Static file serving

    # --- Third-Party Apps ---
    'rest_framework',  # Django REST Framework (DRF) for building APIs
    'drf_yasg',        # Swagger/OpenAPI documentation generator

    # --- Project Apps ---
    'factory',         # Our Digital Twin Factory app
]


# --------------------------------------------------
# Middleware
# These run on every request/response cycle
# --------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# --------------------------------------------------
# URL Configuration
# Points Django to the main URL router
# --------------------------------------------------
ROOT_URLCONF = 'digital_twin_API.urls'


# --------------------------------------------------
# Templates Configuration
# Tells Django how to load and render HTML templates
# --------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],       # Add custom template directories here if needed
        'APP_DIRS': True, # Automatically find templates inside each app's /templates/ folder
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# --------------------------------------------------
# WSGI Configuration
# Entry point for WSGI-compatible web servers (e.g. gunicorn)
# --------------------------------------------------
WSGI_APPLICATION = 'digital_twin_API.wsgi.application'


# --------------------------------------------------
# Database Configuration
# Using SQLite for development (easy, no setup needed)
# --------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # Database file lives in the project root
    }
}


# --------------------------------------------------
# Password Validation
# Rules that enforce strong user passwords
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --------------------------------------------------
# Internationalization
# Language and timezone settings
# --------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True   # Enable Django's translation system
USE_TZ = True     # Store datetimes as timezone-aware


# --------------------------------------------------
# Static Files
# URL prefix for serving CSS, JS, images
# --------------------------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# --------------------------------------------------
# Default Primary Key Field Type
# All models will use BigAutoField (64-bit integer) as default PK
# --------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --------------------------------------------------
# Django REST Framework Settings
# --------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',          # Renders API responses as JSON
        'rest_framework.renderers.BrowsableAPIRenderer',  # Enables the browser-based API UI
    ]
}